### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by missvicki**

### CODE REVIEW

**Comment by kabrick** [comment]
Hey @missvicki, have you created the github pages for it yet?

**Comment by missvicki** [comment]
@kabrick yes i do have a github pages for this branch. i chose to do pull requests for each of my stories

**Comment by missvicki** [comment]
Here is a link to my github pages https://missvicki.github.io/storemanager/UI/

**Comment by kabrick** [comment]
Love the attention to detail and general design of the whole application. And the animations when adding a new product are a nice touch. What i may suggest is if you could make the colours on the dashboard page showing the statistics consistent that would make it much better

**Pull request closed without merging**
